### ISSUE TITLE
SCP-914 Teleportation bug

### ISSUE THREAD

**Issue by Dinspit** [Exiled-Team/Common-Utils#131]
**Describe the bug**
SCP-914 cannot teleport a large number of players. (Approximately 7 players in 914, only 3-5 are teleported, the rest will remain in 914)

**Copy of current CU config section**
```
  # The list of custom 914 recipies. Original is the item being upgraded, New is the item to upgrade to, and Chance is the percent chance of the upgrade happening. You can specify multiple upgrade choices for the same item.
  scp914_item_changes:
    Rough:
    - original: KeycardO5
      new: MicroHID
      chance: 0
      count: 1
  # The list of custom 914 recipies for roles. Original is the role to be changed, New is the new role to assign, Chance is the % chance of the upgrade occuring.
  scp914_class_changes:
    Rough:
    - original: ClassD
      new: 'Spectator'
      chance: 0
      keep_inventory: true
  # The list of 914 teleport settings. Note that if you set "zone" to anything other than Unspecified, it will always select a random room from that zone, instead of the room type defined.
  scp914_teleport_chances:
    Rough:
    - zone: Unspecified
      room: HczTCross
      offset:
        x: 0
        y: 0
        z: 0
      chance: 20
      damage: 20
    - zone: Unspecified
      room: HczCurve
      offset:
        x: 0
        y: 0
        z: 0
      chance: 20
      damage: 20
    - zone: Unspecified
      room: Hcz939
      offset:
        x: 0
        y: 0
        z: 0
      chance: 20
      damage: 20
    - zone: Unspecified
      room: LczClassDSpawn
      offset:
        x: 0
        y: 0
        z: 0
      chance: 15
      damage: 10
    - zone: Unspecified
      room: LczGlassBox
      offset:
        x: 0
        y: 0
        z: 0
      chance: 15
      damage: 10
    - zone: Unspecified
      room: LczToilets
      offset:
        x: 0
        y: 0
        z: 0
      chance: 15
      damage: 10
    - zone: Unspecified
      room: EzGateA
      offset:
        x: 0
        y: 0
        z: 0
      chance: 5
      damage: 40
    - zone: Unspecified
      room: Surface
      offset:
        x: 0
        y: 0
        z: 0
      chance: 5
      damage: 60
  # A dictionary of random effects to apply to players when going through 914 on certain settings.
  scp914_effect_chances:
    Rough:
    - effect: Blinded
      chance: 100
      duration: 3
  # Determines if 914 effects are exclusive, meaning only one can be applied each time a player is processed by 914.
  scp914_effects_exclusivity: false
  # Whether or not SCPs are immune to effects gained from 914.
  scps_immune_to914_effects: false
```

**EXILED Version ("latest" is not a version):**
8.6.0

**Additional context**
The problem is in the plugin code
