### ISSUE TITLE
Config turns to garbage

### ISSUE THREAD

**Issue by Tamago4a** [Exiled-Team/Common-Utils#32]
After starting the server, my config:
```yaml
  starting_inventories:
    ClassD:
      slot1:
      - item_name: KeycardJanitor
        chance: 50
        group: none
      slot2:
      - item_name: Adrenaline
        chance: 1
        group: none
      slot3:
      - item_name: Flashlight
        chance: 6
        group: none
      slot4: []
      slot5: []
      slot6: []
      slot7: []
      slot8: []
    ChaosMarauder:
      slot1:
      - item_name: KeycardChaosInsurgency
        chance: 100
        group: none
      slot2:
      - item_name: GunLogicer
        chance: 100
        group: none
      slot3:
      - item_name: GrenadeFlash
        chance: 20
        group: none
      slot4:
      - item_name: Radio
        chance: 100
        group: none
      slot5:
      - item_name: Flashlight
        chance: 100
        group: none
      slot6:
      - item_name: Medkit
        chance: 100
        group: none
      slot7:
      - item_name: Adrenaline
        chance: 3
        group: none
      slot8:
      - item_name: ArmorHeavy
        chance: 100
        group: none
    Scientist:
      slot1:
      - item_name: KeycardResearchCoordinator
        chance: 20
        group: none
      - item_name: KeycardScientist
        chance: 100
        group: none
      slot2:
      - item_name: Flashlight
        chance: 100
        group: none
      slot3:
      - item_name: Adrenaline
        chance: 10
        group: none
      - item_name: Medkit
        chance: 30
        group: none
      - item_name: Painkillers
        chance: 80
        group: none
      slot4:
      - item_name: GunCOM15
        chance: 2
        group: none
      - item_name: GunRevolver
        chance: 2
        group: none
      - item_name: GunCOM18
        chance: 2
        group: none
      slot5:
      - item_name: Ammo9x19
        chance: 5
        group: none
      slot6:
      - item_name: ArmorLight
        chance: 5
        group: none
      slot7: []
      slot8: []
    FacilityGuard:
      slot1:
      - item_name: KeycardGuard
        chance: 100
        group: none
      slot2:
      - item_name: GunCOM18
        chance: 35
        group: none
      - item_name: GunCOM15
        chance: 100
        group: none
      slot3:
      - item_name: GrenadeFlash
        chance: 20
        group: none
      slot4:
      - item_name: Radio
        chance: 100
        group: none
      slot5:
      - item_name: Flashlight
        chance: 100
        group: none
      slot6:
      - item_name: Adrenaline
        chance: 3
        group: none
      - item_name: Painkillers
        chance: 100
        group: none
      slot7:
      - item_name: ArmorLight
        chance: 100
        group: none
      slot8: []
    NtfPrivate:
      slot1:
      - item_name: KeycardNTFOfficer
        chance: 100
        group: none
      slot2:
      - item_name: GunFSP9
        chance: 100
        group: none
      slot3:
      - item_name: GrenadeFlash
        chance: 20
        group: none
      slot4:
      - item_name: Radio
        chance: 100
        group: none
      slot5:
      - item_name: Flashlight
        chance: 100
        group: none
      slot6:
      - item_name: Adrenaline
        chance: 3
        group: none
      - item_name: Painkillers
        chance: 100
        group: none
      slot7:
      - item_name: ArmorCombat
        chance: 100
        group: none
      slot8: []
    NtfSergeant:
      slot1:
      - item_name: KeycardNTFLieutenant
        chance: 100
        group: none
      slot2:
      - item_name: GunCrossvec
        chance: 100
        group: none
      slot3:
      - item_name: GrenadeFlash
        chance: 20
        group: none
      slot4:
      - item_name: Radio
        chance: 100
        group: none
      slot5:
      - item_name: Flashlight
        chance: 100
        group: none
      slot6:
      - item_name: Painkillers
        chance: 100
        group: none
      slot7:
      - item_name: ArmorCombat
        chance: 100
        group: none
      slot8: []
    NtfCaptain:
      slot1:
      - item_name: KeycardNTFCommander
        chance: 100
        group: none
      slot2:
      - item_name: GunE11SR
        chance: 100
        group: none
      slot3:
      - item_name: GrenadeFrag
        chance: 100
        group: none
      slot4:
      - item_name: Radio
        chance: 100
        group: none
      slot5:
      - item_name: Flashlight
        chance: 100
        group: none
      slot6:
      - item_name: Medkit
        chance: 100
        group: none
      slot7:
      - item_name: MicroHID
        chance: 3
        group: none
      - item_name: Adrenaline
        chance: 3
        group: none
      slot8:
      - item_name: ArmorHeavy
        chance: 100
        group: none
    NtfSpecialist:
      slot1:
      - item_name: KeycardNTFLieutenant
        chance: 100
        group: none
      slot2:
      - item_name: GunCrossvec
        chance: 100
        group: none
      slot3:
      - item_name: GrenadeFlash
        chance: 20
        group: none
      slot4:
      - item_name: Radio
        chance: 100
        group: none
      slot5:
      - item_name: Flashlight
        chance: 100
        group: none
      slot6:
      - item_name: Medkit
        chance: 100
        group: none
      slot7:
      - item_name: Adrenaline
        chance: 100
        group: none
      slot8:
      - item_name: ArmorCombat
        chance: 100
        group: none
    ChaosConscript:
      slot1:
      - item_name: KeycardChaosInsurgency
        chance: 100
        group: none
      slot2:
      - item_name: GunAK
        chance: 100
        group: none
      slot3:
      - item_name: GrenadeFlash
        chance: 20
        group: none
      slot4:
      - item_name: Radio
        chance: 100
        group: none
      slot5:
      - item_name: Flashlight
        chance: 100
        group: none
      slot6:
      - item_name: Medkit
        chance: 100
        group: none
      slot7:
      - item_name: Adrenaline
        chance: 3
        group: none
      slot8:
      - item_name: ArmorCombat
        chance: 100
        group: none
    ChaosRifleman:
      slot1:
      - item_name: KeycardChaosInsurgency
        chance: 100
        group: none
      slot2:
      - item_name: GunAK
        chance: 100
        group: none
      slot3:
      - item_name: GrenadeFlash
        chance: 20
        group: none
      slot4:
      - item_name: Radio
        chance: 100
        group: none
      slot5:
      - item_name: Flashlight
        chance: 100
        group: none
      slot6:
      - item_name: Medkit
        chance: 100
        group: none
      slot7:
      - item_name: Adrenaline
        chance: 3
        group: none
      slot8:
      - item_name: ArmorCombat
        chance: 100
        group: none
    ChaosRepressor:
      slot1:
      - item_name: KeycardChaosInsurgency
        chance: 100
        group: none
      slot2:
      - item_name: GunShotgun
        chance: 100
        group: none
      slot3:
      - item_name: GrenadeFlash
        chance: 20
        group: none
      slot4:
      - item_name: Radio
        chance: 100
        group: none
      slot5:
      - item_name: Flashlight
        chance: 100
        group: none
      slot6:
      - item_name: Medkit
        chance: 100
        group: none
      slot7:
      - item_name: Adrenaline
        chance: 3
        group: none
      slot8:
      - item_name: ArmorCombat
        chance: 100
        group: none
```
Turns into this garbage:
```yaml
  starting_inventories:
    ClassD:
      slot1:
      - item_name: KeycardJanitor
        chance: 50
        group: none
      slot2:
      - item_name: Adrenaline
        chance: 1
        group: none
      slot3:
      - item_name: Flashlight
        chance: 6
        group: none
      slot4: []
      slot5: []
      slot6: []
      slot7: []
      slot8: []
    ChaosMarauder:
      slot1:
      - &o10
        item_name: KeycardChaosInsurgency
        chance: 100
        group: none
      slot2:
      - item_name: GunLogicer
        chance: 100
        group: none
      slot3:
      - &o1
        item_name: GrenadeFlash
        chance: 20
        group: none
      slot4:
      - &o2
        item_name: Radio
        chance: 100
        group: none
      slot5:
      - &o0
        item_name: Flashlight
        chance: 100
        group: none
      slot6:
      - &o6
        item_name: Medkit
        chance: 100
        group: none
      slot7:
      - &o3
        item_name: Adrenaline
        chance: 3
        group: none
      slot8:
      - &o7
        item_name: ArmorHeavy
        chance: 100
        group: none
    Scientist:
      slot1:
      - item_name: KeycardResearchCoordinator
        chance: 20
        group: none
      - item_name: KeycardScientist
        chance: 100
        group: none
      slot2:
      - *o0
      slot3:
      - item_name: Adrenaline
        chance: 10
        group: none
      - item_name: Medkit
        chance: 30
        group: none
      - item_name: Painkillers
        chance: 80
        group: none
      slot4:
      - item_name: GunCOM15
        chance: 2
        group: none
      - item_name: GunRevolver
        chance: 2
        group: none
      - item_name: GunCOM18
        chance: 2
        group: none
      slot5:
      - item_name: Ammo9x19
        chance: 5
        group: none
      slot6:
      - item_name: ArmorLight
        chance: 5
        group: none
      slot7: []
      slot8: []
    FacilityGuard:
      slot1:
      - item_name: KeycardGuard
        chance: 100
        group: none
      slot2:
      - item_name: GunCOM18
        chance: 35
        group: none
      - item_name: GunCOM15
        chance: 100
        group: none
      slot3:
      - *o1
      slot4:
      - *o2
      slot5:
      - *o0
      slot6:
      - *o3
      - &o4
        item_name: Painkillers
        chance: 100
        group: none
      slot7:
      - item_name: ArmorLight
        chance: 100
        group: none
      slot8: []
    NtfPrivate:
      slot1:
      - item_name: KeycardNTFOfficer
        chance: 100
        group: none
      slot2:
      - item_name: GunFSP9
        chance: 100
        group: none
      slot3:
      - *o1
      slot4:
      - *o2
      slot5:
      - *o0
      slot6:
      - *o3
      - *o4
      slot7:
      - &o5
        item_name: ArmorCombat
        chance: 100
        group: none
      slot8: []
    NtfSergeant:
      slot1:
      - &o8
        item_name: KeycardNTFLieutenant
        chance: 100
        group: none
      slot2:
      - &o9
        item_name: GunCrossvec
        chance: 100
        group: none
      slot3:
      - *o1
      slot4:
      - *o2
      slot5:
      - *o0
      slot6:
      - *o4
      slot7:
      - *o5
      slot8: []
    NtfCaptain:
      slot1:
      - item_name: KeycardNTFCommander
        chance: 100
        group: none
      slot2:
      - item_name: GunE11SR
        chance: 100
        group: none
      slot3:
      - item_name: GrenadeFrag
        chance: 100
        group: none
      slot4:
      - *o2
      slot5:
      - *o0
      slot6:
      - *o6
      slot7:
      - item_name: MicroHID
        chance: 3
        group: none
      - *o3
      slot8:
      - *o7
    NtfSpecialist:
      slot1:
      - *o8
      slot2:
      - *o9
      slot3:
      - *o1
      slot4:
      - *o2
      slot5:
      - *o0
      slot6:
      - *o6
      slot7:
      - item_name: Adrenaline
        chance: 100
        group: none
      slot8:
      - *o5
    ChaosConscript:
      slot1:
      - *o10
      slot2:
      - &o11
        item_name: GunAK
        chance: 100
        group: none
      slot3:
      - *o1
      slot4:
      - *o2
      slot5:
      - *o0
      slot6:
      - *o6
      slot7:
      - *o3
      slot8:
      - *o5
    ChaosRifleman:
      slot1:
      - *o10
      slot2:
      - *o11
      slot3:
      - *o1
      slot4:
      - *o2
      slot5:
      - *o0
      slot6:
      - *o6
      slot7:
      - *o3
      slot8:
      - *o5
    ChaosRepressor:
      slot1:
      - *o10
      slot2:
      - item_name: GunShotgun
        chance: 100
        group: none
      slot3:
      - *o1
      slot4:
      - *o2
      slot5:
      - *o0
      slot6:
      - *o6
      slot7:
      - *o3
      slot8:
      - *o5
```
At the same time, everything seems to be working...
